id: P005429
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W24025
  title: འབའ་ར་དཀར་བརྒྱུད་ཀྱི་ཆོས་སྤྱོད
  author: ''
  volumes:
    0ae03fd8895d4f9c8779be24ac7b2ed8:
      image_group_id: I3665
      title: ''
      volume_number: 1
      total_pages: 558
      base_file: v001.txt
